#!/bin/sh

# check if the developer really want to commit go.mod
# is there a staged go.mod file?
go_mod_staged="$(git diff --cached --name-only | grep -c -E '\go.mod$')"

if [[ $go_mod_staged -eq 0 ]] ; then
	exit 0
fi

# backup original go.mod
cp ./go.mod /tmp/go.mod 

# only remove local references. i sometimes need to use replace for reasons other than
# local references like using a previous stable version of a package etc.
sed -i '/replace .* => [/.].*/d' go.mod

# stage changed go.mod file again
git add go.mod